### ISSUE TITLE
Suggestion - Add new display mode

### ISSUE THREAD

**Issue by monecchi** [bhendi-boi/tailwindcss-displaymodes#1]
First thing first, thanks for the plugin! 

I'm developing a PWA app with the UX focused on Desktop. The issue is it seems there's no offcial MDN, W3C way to specifically detect a pwa that has been installed on a desktop from a browser, so the options would be either using a JS workaround method or combined media queries.

On my pwa set up, I've chosen to have the "standalone" mode and the "Window-Controls-Overlay" feature enabled, please check [here](https://intercom.help/progressier/en/articles/7999596-understanding-pwa-display-modes), and [here](https://intercom.help/progressier/en/articles/6034436-using-window-controls-overlay-in-your-app-manifest) regarding the latter one.

As a result, it allows me to make use of a media query to target that specific feature, as follows:

```css
@media all and (display-mode: window-controls-overlay) { 
    .app-header { 
       background-color: #fafafa;
    }
}
```
My goal was to be able to define some styling only when on standalone mode on Desktop! I've tried combined media queries as such with no success, so I ended up using a JS solution to solve the issue.

```css
@media all and (display-mode: standalone) and (display-mode: window-controls-overlay) { 
    .app-header { 
       background-color: #fafafa;
    }
}
```
Although the first snippet above works, it only applies the styles if and when the window controls are on, and as long as the user is able to toggle it on/off, it is not something we can totally rely on for a permanent styling.

However, based on that condition, we can set styles specifically when the "Window-Controls-Overlay" feature is toggled on or off and that would be of a great help to have something like bellow implemented on the plugin.

```js
plugin(function ({ addVariant }) {
  addVariant('browser_standalone', '@media all and (display-mode: window-controls-overlay)')
})
```
